---
title: "Introduction"
---

Along with growing interests in healthy life and animal protection, the concept of "Vegetarian" or "Vegan" has become more and more familiar among people. Nowadays, we often see the vegetarian or vegan menus in restaurants. Also, observing the expansion of vegans, "The Economist" said that 2019 would be ["the Year of the Vegan."](https://worldin2019.economist.com/theyearofthevegan) Therefore, it is worth exploring the data about vegetarian or vegan restaurants, recipes, and profiles.

First of all, this website examines the [interest trend](https://sun-wenjun.github.io/vegetarian_visualization_project/trend.html) of vegetarian on websites, and the [personal character](https://sun-wenjun.github.io/vegetarian_visualization_project/demographic.html) of vegetarian or vegan. Next, implementing the text analysis on [vegetarian recipes](https://sun-wenjun.github.io/vegetarian_visualization_project/recipe.html), it is revealed what kind of ingredients are most likely included. Finally, the locations of vegetarian or vegan restraunts in New York state, and its relationships with [political ideologies](https://sun-wenjun.github.io/vegetarian_visualization_project/ideology.html) and [poverty conditions](https://sun-wenjun.github.io/vegetarian_visualization_project/income.html), are visualized.
